import { ManufacturingPreset } from "./types";

export const MANUFACTURING_PRESETS: ManufacturingPreset[] = [
  {
    name: "Precision CNC Machining",
    segment: "machining",
    description: "SME workshop specializing in structural alloy milling, turning, and high-tolerance components.",
    defaults: {
      segment: "machining",
      productionVolume: 2500,
      materialWeight: 12500,
      materialType: "Alloy Steel & Aluminum 6061-T6",
      gridElectricity: 18500,
      solarElectricity: 4500,
      dieselFuel: 420,
      machiningHours: 320,
      transportDistance: 850,
      cargoWeight: 12,
      generalWaste: 1850,
      hazardousWaste: 380,
    },
  },
  {
    name: "Plastics Injection Molding",
    segment: "plastics",
    description: "High-volume polymer fabrication producing consumer casings, custom gears, and industrial seals.",
    defaults: {
      segment: "plastics",
      productionVolume: 15000,
      materialWeight: 22000,
      materialType: "Polypropylene (PP) & Polycarbonate (PC)",
      gridElectricity: 34000,
      solarElectricity: 8000,
      dieselFuel: 150,
      machiningHours: 540,
      transportDistance: 1200,
      cargoWeight: 18,
      generalWaste: 3100,
      hazardousWaste: 90,
    },
  },
  {
    name: "Heavy Foundry & Smelting",
    segment: "foundry",
    description: "Metal sand-casting and mold smelting workshop casting iron casings and structural components.",
    defaults: {
      segment: "foundry",
      productionVolume: 800,
      materialWeight: 45000,
      materialType: "Recycled Cast Iron & Structural Steel Scrap",
      gridElectricity: 58000,
      solarElectricity: 12000,
      dieselFuel: 2100,
      machiningHours: 420,
      transportDistance: 1800,
      cargoWeight: 42,
      generalWaste: 8500,
      hazardousWaste: 1200,
    },
  },
  {
    name: "PCB & Electronics Assembly",
    segment: "electronics",
    description: "Precision automated Surface-Mount Technology (SMT) lines producing integrated circuit boards.",
    defaults: {
      segment: "electronics",
      productionVolume: 5000,
      materialWeight: 1500,
      materialType: "FR4 Fiberglass Boards, Copper Foil, Solder Paste",
      gridElectricity: 14500,
      solarElectricity: 3500,
      dieselFuel: 80,
      machiningHours: 240,
      transportDistance: 3200,
      cargoWeight: 1.5,
      generalWaste: 450,
      hazardousWaste: 210,
    },
  },
  {
    name: "Industrial Textile Weaving",
    segment: "textiles",
    description: "Fibre milling and high-speed mechanical loom weaving weaving synthetic canvas & tech fabric roles.",
    defaults: {
      segment: "textiles",
      productionVolume: 8500,
      materialWeight: 18000,
      materialType: "Synthetic Polyester Filament & Organic Cotton blend",
      gridElectricity: 22000,
      solarElectricity: 6000,
      dieselFuel: 350,
      machiningHours: 480,
      transportDistance: 950,
      cargoWeight: 15,
      generalWaste: 2400,
      hazardousWaste: 150,
    },
  },
];
